{% set name = "commonmarker" %}
{% set version = "0.21.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 39faa41ef4838a2e9dca5855fc3780c39beeab29a551b7e37b725c899e8aaca2

build:
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
    - make -C {{ PREFIX }}/lib/ruby/gems/{{ ruby }}.0/gems/{{ name }}-{{ version }}/ext/{{ name }} clean
  skip: {{ win }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - ruby
  run:
    - ruby
    - rb-ruby-enum >=0.5,<1

test:
  commands:
    - commonmarker --help
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: A fast, safe, extensible parser for CommonMark. This wraps the official libcmark library.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/gjtorikian/{{ name }}

extra:
  recipe-maintainers:
    - sodre
