travis:
  secure:
    BINSTAR_TOKEN: Xe1iWHU1QVhAtnR5GuOU8UKze8Y2H/V429gt/FfiPuZUwHQasMTkQQGo0+goTSD8MoS3AT8hQySFiCh2vrlHxKI29CxVNwaDEHMQqOJwDmGUcMgNndGtW95qe3uST99Gbj2W7uVZp2RNjeRg/9vnl9+MBSDZsgG28vMm+yQJ9WHBJprRU/KNk8cHR2bmbJp7SrOopeh47D1vMJ2VUPQAPncXR3yDT3R33Q9rSmZRfx/D0ghekl4bkURdEaJW4FicTzBIXdlF8HbGOsTdD7G03KamQRSYm2/yKEC3kWPDAeoAcFW8jSIhLwv7VrCnBEwUezgzDBDwDpPk1XSa8CFrnOtGQRagsRlZhLd2VtNwOE3WRyt3vlgyegz5vnjlfvBXL3LRUAtvkl1eb3Asqh+LyJEaZRh7ffyeT3L6MwHsuvvokDaYONk2v9BNdL9S2j9P4+05xYPITO+tivWLYey0LVN9UGNITpIjvp9znsrnnggYLhY3zgbPtALJHG+CYTz9F2gPlFciKrJe0mX+Ou0t8/aK9WR2hD2qRpxUupPbpdW1n3w7DYAUJkIcuqqdXG5KbcXJ20HUBarYhEHMtybhTpZJcAH30d5zLjjm+eC0Al+ytlot3LYT9YN1nlx07hLGQ4w1eNIq0AGCpiRD6lgMEwjL+2WW5ArdXM4W3lesTtc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
